# -*- coding: utf-8 -*-
"""1302 assignment 07.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AR26j8GyKiGZCRN8UzDahx8XJJqNPr4I

# "This is Assignment 07 - LeAnne Rheaume"

## Assignment 07 requirements -

#### **Requirement 1:** From range(30), use list comprehension to output a list with numbers that are not multiples of 3 and not equal to 13 and not equal to 17.

#### **Requirement 2:** Write the operation in the previous Requirement but using loop syntax instead of list comprehension.

#### **Requirement 3:** From range(30), use list comprehension to output a list with positive numbers that are even and negative numbers that are odd.

#### **Requirement 4**: From range(1000), use set comprehension to output a set of numbers where i % 5 == 0.

#### **Requirement 5:** From range(20), use dictionary comprehension to output a dictionary of numbers (i) as keys and their cubes (i**3) as values.

#### **Requirement 6:** From range(50), use a generator function to create a generator named G of even numbers, print the type of G, and then print the contents of G.

#### **Requirement 7:**  From range(15), use a generator in two ways to output n/2. For example, as G1 = (…) and G2 = gen_divby2().

#### **Requirement 8:** Use a generator defined as a function to output prime numbers < 100.

#### **Requirement 9:** Import the following modules from Python’s Standard Library. Demonstrate a minor example using functionality/capability from each module in the list below:

* os and sys: Tools for interfacing with the operating system, including navigating file directory structures and executing shell commands
* math and cmath: Mathematical functions and operations on real and complex numbers
* itertools: Tools for constructing and interacting with iterators and generators
* functools: Tools that assist with functional programming
* random: Tools for generating pseudorandom numbers
* pickle: Tools for object persistence: saving objects to and loading objects from disk
* json and csv: Tools for reading JSON-formatted and CSV-formatted files.
* urllib: Tools for doing HTTP and other web requests

####**Requirement 10:** Using string methods:
* Demonstrate the conversion to upper-case and lower-case
* Convert “this is the title of my latest novel” to a title
* Removing leading and trailing spaces
* Remove leading zeros
* Return the index of a substring
* Determine if a string ends with and begins with a substring
* Replace a substring with another substring
* Split a string of words into a list of individual words
* Join a list into a string using ** as separators
* Print list elements each on its own line using join()
* Define pi = ‘3.14159265359’ Use format() to print pi to 7 decimal places to
the right of the decimal point.

####**Requirement 11:** Use the Regular Expression compile() method to create an email matcher and demonstrate the matcher with 3 valid emails and 3 invalid emails.

####**Requirement 12:** Use markdown to include a statement at the end of assignment-07.ipynb explaining your experiences with Assignment 07. Make this authentic (minimum of 2-3 sentences).
**TEST – TEST – TEST** your .ipynb file to ensure all requirements are met. Produce an .html file from a successful test run of the .ipynb file. Ensure that the .html is produced correctly by opening it in a browser.
* Use the list above as a confirmation checklist.
* Not meeting all requirements = 0 points for the assignment.

# Assignment 07 code
"""

from re import RegexFlag
from __future__ import print_function
#Assignment 07 -
import numbers
import math
import numpy as np
import pickle
from itertools import count
import functools
import random
import os
import sys
import urllib
import csv
import json

#range of 30, list comprehension set up
list_iteration = [i for i in range(30) if i % 3 != 0 and i != 13 and i != 17]
#loop syntax of list iteration
list_iteration_loop = []
for i in range(30):
    if i % 3 != 0 and i != 13 and i != 17:
        list_iteration_loop.append(i)
# positive and negative list iteration
positive_even = [i for i in range(30) if i % 2 == 0 and i % 3 != 0]
negative_odd = [-i for i in range(1,30,2)]
#print testing
print (list_iteration)
print (list_iteration_loop)
print (positive_even)
print (negative_odd)

#range(1000) set comprehension
set_comp = {i for i in range(1000) if i % 5 == 0}
print(set_comp)

# range(20) dictionary comprehension
cube_dict = {i: i**3 for i in range(20)}
print(cube_dict)

#generator function for range (50)
gen_function = (i for i in range(50) if i % 2 == 0)
print(type(gen_function))
print(list(gen_function))

#even numbers generator setup
def even_numbers_generator(limit):
    for i in range(limit):
        if i % 2 == 0:
            yield i
def odd_numbers_generator(limit):
    for i in range(limit):
      if i / 2 != 0:
        yield i
# generator snippet in action
G = even_numbers_generator(15)
print(type(G))
for num in G:
    print(num)

# From range(15), use a generator in two ways to output n/2. For example, as G1 = (…) and G2 = gen_divby2().

# Main gen div snippet
def gen_divby2():
    for n in range(15):
        yield n / 2

# First way: using next()
print("First way:")
G1 = gen_divby2()
for _ in range(15):
    print(next(G1))

# Second way: using for loop
print("Second way:")
G2 = gen_divby2()
for value in G2:
    print(value)

#Use a generator defined as a function to output prime numbers < 100 using itertools
print("Prime Generator:")
def prime_generator():
    count = 3
    yield 2
    while count < 100:
        isprime = True
        for i in range(2, count):
            if count % i == 0:
                isprime = False
                break
        if isprime:
            yield count
        count += 1
#using the prime generator in a snippet; it populated from colab so I think it pulled from the datascience github linked up in the header via MIT license
for prime in prime_generator():
    print(prime)

from os import path
from urllib.request import urlretrieve
import json
# Import the json module

from sys import version_info
from platform import python_version
from math import pi

print("Using strings and libraries:")

#print pi
print(f'The value of pi is approximately {math.pi:.3f}.')

# join method for a list
join_list = ["a", "b", "c", "d", "e", "f","g",]
separator = "**"
result_filter = separator.join(join_list)
from __future__ import print_function
#Assignment 07 -
import numbers
import math
import numpy as np
import pickle
from itertools import count
import functools
import random
import os
import sys
import urllib
import csv
import json

#range of 30, list comprehension set up
list_iteration = [i for i in range(30) if i % 3 != 0 and i != 13 and i != 17]
#loop syntax of list iteration
list_iteration_loop = []
for i in range(30):
    if i % 3 != 0 and i != 13 and i != 17:
        list_iteration_loop.append(i)
# positive and negative list iteration
positive_even = [i for i in range(30) if i % 2 == 0 and i % 3 != 0]
negative_odd = [-i for i in range(1,30,2)]
#print testing
print (list_iteration)
print (list_iteration_loop)
print (positive_even)
print (negative_odd)

#range(1000) set comprehension
set_comp = {i for i in range(1000) if i % 5 == 0}
print(set_comp)

# range(20) dictionary comprehension
cube_dict = {i: i**3 for i in range(20)}
print(cube_dict)

#generator function for range (50)
gen_function = (i for i in range(50) if i % 2 == 0)
print(type(gen_function))
print(list(gen_function))

#even numbers generator setup
def even_numbers_generator(limit):
    for i in range(limit):
        if i % 2 == 0:
            yield i
def odd_numbers_generator(limit):
    for i in range(limit):
      if i % 2 != 0:
        yield i
# generator snippet in action
G = even_numbers_generator(15)
print(type(G))
for num in G:
    print(num)

# From range(15), use a generator in two ways to output n/2. For example, as G1 = (…) and G2 = gen_divby2().

# Main gen div snippet
def gen_divby2():
    for n in range(15):
        yield n / 2

# First way: using next()
print("First way:")
G1 = gen_divby2()
for _ in range(15):
    print(next(G1))

# Second way: using for loop
print("Second way:")
G2 = gen_divby2()
for value in G2:
    print(value)

#Use a generator defined as a function to output prime numbers < 100 using itertools
print("Prime Generator:")
def prime_generator():
    count = 3
    yield 2
    while count < 100:
        isprime = True
        for i in range(2, count):
            if count % i == 0:
                isprime = False
                break
        if isprime:
            yield count
        count += 1
#using the prime generator in a snippet; it populated from colab so I think it pulled from the datascience github linked up in the header via MIT license
for prime in prime_generator():
    print(prime)

from os import path
from urllib.request import urlretrieve
import json
# Import the json module

from sys import version_info
from platform import python_version
from math import pi

print("Using strings and libraries:")

#print pi
print(f'The value of pi is approximately {math.pi:.3f}.')

# join method for a list, splitting string of words, concat,
print("Join list, spliting strings, etc.")
join_list = ["pigs", "is", "pigs", "is", "a", "beloved", "disney", "classic", "short"]
separator = "**"
result_filter = separator.join(join_list)
print(result_filter)

#email

import re #regex updated module

# Compile the email regex pattern
email_pattern = re.compile(r"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$")

# Valid emails
valid_emails = ["test@example.com", "pigsPigs@domain.org", "meep@domain.co.ru"]

# Invalid emails
invalid_emails = ["invalid_email", "no_at_symbol@com", "test@.com"]

# Test the matcher
print("Valid emails:")
for email in valid_emails:
    if email_pattern.match(email):
        print(f"'{email}' is a valid email")
    else:
        print(f"'{email}' is NOT a valid email")

print("\nInvalid emails:")
for email in invalid_emails:
    if email_pattern.match(email):
        print(f"'{email}' is a valid email")
    else:
        print(f"'{email}' is NOT a valid email")

#printing titles from a string
new_var = "Pigs is pigs but they dont have thumbs so they do not need emails"
print(new_var.title())
print(new_var.upper())
print(new_var.lower())

"""# Thoughts on the Assignment

#### I had to rely fairly heavily on a combination of resources to solve the requirements for the assignments. There were some places where colab and the book and I had to do the work sort of like a group project. There's definitely a learning curve with understanding which module does what, and when to call them. You'll see in my work that I called a github component in looking for help to solve some requirements. I know this is similar to what real world working in software development is like, but I do also really have a hard time understanding certain things like the mathmatics involved, as I am old, and I didn't do well in math at any stage of my career or education. I like the satisfaction of getting the answer, and with exploring the capabilities of different methods or strings. I do feel I am getting the hnag of knowing the difference between some of the terms. I also realize that there's historical precedent that python pulls from, and I didn't know that really prior to researching. I didn't know what the ' Sieve of Eratosthenes' was prior to this assignment, for example. Or what the Sapir-Whorf hypothesis was, and being frank, I still don't quite know. But I like that I'm learning more than just how to plug characters and numbers into a compiler and calling it a day!
"""