# -*- coding: utf-8 -*-
"""lrheaume_assignment05_ITSE1302

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Wxbu_YjlyBuacbRJcQDfvew8GMe8WII

# Assignment 05 - LeAnne Rheaume
## Requirements - whirlwind tour of python, chapter 00-10
### From assignment 1302 content reqs part 1: Demonstrate the following arithmetic operations in a cell - addition, subtraction, multiplication, true division, floor division, exponentiation
"""

#operators lib reference for assignment 05
import math
import operator
from IPython.display import display

#Assign values to the global variables
a = 10
b = 6
c = 6
d = 8
e = 9

# Addition
def add(a, b):
    return a + b
print("Addition:",)
# Subtraction
def subtract(a, b):
    return a - b
print("Subtraction:", )

# Multiplication
def multiply(a, b):
    return a * b
print("Multiplication:",)

# Division
def divide(a, b):
    if b == 0:
        raise ValueError("cannot divide by zero!")
    return a / b
print("Division:",)

#Exponentiation
def power(a, b):
    return a**b
print("Power raising to another number",)

# Floor Division
def floor_divide(a, b):
    if b == 0:
        raise ValueError("Cannot perform floor division by zero")
    return a // b
print("Floor Division:", )

# Modulo
def modulo (a,b):
    if b == 0:
        raise ValueError("Cannot perform modulo by zero.")
    return a % b
print("Modulo:", )

#fuctions and printing results from operators
addition = add(a,b)
subtraction = subtract(a,b)
multiplication = multiply(a,e)
division = divide(a,b)
exponentiation = power(a,b)
floor_division = floor_divide(b, b)
modulo = modulo(a,d)
print(a + b)
print(a // b)
print(a % b)
print(a ** b)
print(modulo)
print(floor_division)
print(exponentiation)
print(division)
print(multiplication)
print(subtraction)
print(addition)

# Call main if it's defined
if __name__ == "__main__":
  def main():
# Get user input with a clear prompt
    pass

# Print the calculated values
print(addition, a + b)
def question():
  question()
  print(input("please input your answer to the following:"))
  #I have gotten myself turned around, moving on to second part since I think I've got part 1 done in the block above

# is a and b equal to one another? T/f
a == b

# is a and b equal to one another? T/f
a != b

# is a and b greater than or equal to one another? T/f
a <= b

# is a and b greater than or equal to one another? T/f
a >= b

# is a less than b? T/f
a < b

# is a greater than b? T/f
a > b

#integer list for use in the part 2:

list1 = [19,72,56,47,57,9,11,3,44,21,]
list2 = [44,21,9,7,1,66,88,1332,6,33]
#integer list for use in the part 2:

list1 = [19,72,56,47,57,9,11,3,44,21,]
list2 = [44,21,9,7,1,66,88,1332,6,33]

#list for even numbers
list_even = []
for num in list1 + list2:
    # Iterate through both lists
    if num % 2 == 0:
        list_even.append(num)
        print(list_even)

#list for odd numbers
list_odd = []
for num in list1 + list2:
    if num % 2 == 0:
        list_even.append(num)
    else:
        list_odd.append(num)
        print(list_odd)

# Define the is_integer function before calling it
def is_integer(n):
    return (n, int)

is_integer(n=list_odd[0]) #list_odd is a list, so you must access one of its element to check for its type

# Check if all elements in list_odd are integers
all_integers = all(is_integer(x) for x in list_odd)
print(all_integers)
# Print True if all elements are integers, otherwise False
if num % 2 == 0:
        list_even.append(num)
        print(list_even)

is_integer(n=list_odd)
# Check if all elements in list_odd are integers
all_integers = all(is_integer(x) for x in list_odd)
print(all_integers)
# Print True if all elements are integers, otherwise False

# Testing bool, identity, and membership operations with the lists.

#variables for list checking
list1 = [19,72,56,47,57,9,11,3,44,21,]
list2 = [44,21,9,7,1,66,88,1332,6,33]

combined_list = (list1 + list2)

a = list1
b = list2
c = combined_list

for int in combined_list:
  add(a, b)
print(combined_list)

if a == b:
  print(True,"Accurate.")
else:
  print(False)

if a is b:
  print(True)
else:
  print(False)

if a in b:
  print(True)
else:
  print(False)

if a not in b:
  print(True)
else:
  print(False)
if a is not b:
  print(True)
else:
  print(False)

while a == b:
  print(True)
else:
  print(False)
if a is b:
  print(True)
else:
  print(False)

# ObjectIdentity = a != b >= c = makes a runtime error, infinite loop!~
#variable precision test is 'ObjectIdentity = a, b >= c' etc.
ObjectIdentity = a, b >= c
hex(id(c))
print(hex(id(c)))
print(ObjectIdentity)
while ObjectIdentity == True:
  print(True,"Accurate.")
else:
  print(False, "Try again.")

#testing concatenation
combined_list.sort()
print(combined_list)
combined_list.reverse()
print(combined_list)
len(combined_list)
str(combined_list)
combined_list.count(9)
combined_list.index(11)
#tested suggested items, program I believe is functional.

"""I had a hard time with setting up operators and the internet and the explanation tools in colab did not indicate exactly what to do, so lost some time with fighting initialization, directories, and modules. Once I understood I was trying to do way too much and experiencing scope creep, I clears the unimportant sections and then it went smoother. I am still not 100% if I have it completely handled, but I realized that I needed to get things rolling and figured I would be able to submit and get feedback, then realized I did the wrong assignments.

I've had a rough couple weeks so doing my best to study and catch up. I would love to see a little more time with the operators and how to mess with modules. Like, is there a standard for most programs like established boilerplate recommendations? Just having a hard time with the abstractions.

It was immensely satisfying to get it rolling through! I would also like to understand how to make a prompting system with these, where the user and program would have a back and forth exchange based on things input.
"""